language: php
php:
  - '7.2'

sudo: required
distro: trusty

addons:
  chrome: stable

install:
  - touch database/database.sqlite
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  #- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan migrate:refresh --seed
  - php artisan db:seed --class=TestDataSeeder
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk
