language: php
php:
  - '7.2'
cache:
  directories:
    - $COMPOSER_CACHE_DIR
    - $HOME/.cache/composer/files

sudo: required
distro: trusty

addons:
  chrome: stable

install:
  - touch /tmp/database.sqlite
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  # Run chromedriver using X virtual framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

  # Run application using testing environment
  - export APP_ENV=testing
  - php artisan migrate:refresh --seed
  - php artisan db:seed --class=TestDataSeeder
  - php artisan serve >/dev/null 2>&1 &

script:
  - vendor/bin/phpunit
  - php artisan dusk

deploy:
  provider: heroku
  api_key:
    secure: CdO/LDIsRg928d5K5wreO4RcWj9FgV6m8CLo/QFKw1s4ELNS/0umof821kaIQLyzkWo67iCr7HuqeH0mAK14+I3qXSuDhI/pkMKC9kKkF213091c+kSI/UA9mJIJAHfIW890SgUSvhxQvmRmiuFLHSueBavoON1s2vQwYbK+h+z70NIyMPevQEn3cXBH3k1CXbiVFx219EeQEVfNaVfZWORrpE3lC/+HKlPbOPgH/1psMl0uO/kSIbXYiJ3Io0e9nmQBruWjPKtMXQ/PvQs2AVQ1hQEPSkgJr9Kr65Mk1hmw5JPkpdI9ByZPtx/Evu04Rt/2Hc0Js1HPIqM/ZRKdwli9tCdM9VWUBL29/zhh7CrrMp6webWLkMLAN60iiuOCGD2Qzq8mVmUMq1wCb2+MHbmJWa4SOd+hVD8wO2fEEK/Z4NkIqRFwdCS98QfVKv4bLxEP1X0zA5wekAl3cqpSYDHNl4z2PuMNeVb8HnHG9nBzE12s+WoqFZLkrh2j20S9VrXMMlZYnSz3YwRF5XtXoXBchrwOjpHR8mM8gvSrwTBYnAVCxxwyjYuaEg5J/lHixLhtAWoGVe9+5SsegG/h0mUAmdDzD02x8iRn9YWcQI34eLM4Njp8mIkRG0o1PuiLnA1qBXwlTIlKkk5no1i0N7AnVsP9I2+7FR5IxcJyLZk=
  app: hive-food
